### ISSUE TITLE
Support for Linux ARM64

### ISSUE THREAD

**Issue by XavierGeerinck** [Farama-Foundation/Arcade-Learning-Environment#483]
Hi All!

Thank you for this amazing project. I am just wondering, is Linux ARM64 supported? I am trying to compile and install it myself with the below, but it appears that the ROMs are not found then:

```bash
# Install dependencies for building ALE
RUN apt update && \
    apt install -y python3 python3-pip git cmake libsdl2-dev libboost-all-dev

# Clone the ale-py repository
RUN git clone https://github.com/mgbellemare/Arcade-Learning-Environment.git /ale

RUN cd ale \
    && pip install . \
    && python setup.py bdist_wheel
```

Which results in when starting a program

```
/usr/local/lib/python3.8/site-packages/gymnasium/envs/registration.py:604: UserWarning: WARN: plugin: shimmy.registration:register_gymnasium_envs raised Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 602, in load_plugin_envs
    fn()
  File "/usr/local/lib/python3.8/site-packages/shimmy/registration.py", line 263, in register_gymnasium_envs
    _register_atari_envs()
  File "/usr/local/lib/python3.8/site-packages/shimmy/registration.py", line 207, in _register_atari_envs
    _register_atari_configs(
  File "/usr/local/lib/python3.8/site-packages/shimmy/registration.py", line 131, in _register_atari_configs
    from ale_py.roms import utils as rom_utils
ModuleNotFoundError: No module named 'ale_py.roms'
```

**Comment by JesseFarebro** [comment]
Hi @XavierGeerinck,

There shouldn't be a problem with ARM64. We already publish ARM wheels for macOS.

Are you sure there's not a local directory named `ale_py`? Can you try to install via `pip` with verbose mode enabled, i.e., `pip install . --verbose`, and post the logs here?

Also, if you can post the exact Dockerfile that's able to reproduce the bug, I could also take a look at that.

**Comment by XavierGeerinck** [comment]
Hi! Thanks a lot for coming back so soon. I got it working eventually with the below

```
# Install dependencies for building ALE
RUN apt update && \
    apt install -y python3 python3-pip git cmake libsdl2-dev libboost-all-dev

# Clone the ale-py repository
RUN git clone https://github.com/mgbellemare/Arcade-Learning-Environment.git /ale

# Build ale-py and package it as wheel
RUN mkdir /tmp/ale-build \
    && cd /tmp/ale-build \
    && cmake -DUSE_SDL=OFF -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=OFF /ale \
    && make \
    && cd /ale \
    && pip install .
```

**Comment by JesseFarebro** [comment]
As ARM datacenter processors are becoming ever more popular I plan on releasing prebuilt wheels for `manylinux_aarch64` next release.

**Comment by pseudo-rnd-thoughts** [comment]
@andywatts would you be able to make a PR for this? 
It should be necessary to just update the GitHub/actions/build script for generating wheels

**Comment by gkennickell** [comment]
I wanted to check-in on if shipping a prebuilt wheel for arm64 is still on the roadmap?

I recently ran into the following issue on an arm64 ubuntu system:
- build and install from source works as expected
- installing ale-py via pip results in:

ImportError: cannot import name 'ALEInterface' from 'ale_py' (unknown location)

I checked https://pypi.org/project/ale-py/#files and I did not find a manylinux_aarch64 wheel, only x86_64. Also testing a binary-only install with target --platform manylinux2014_aarch64 results in:
ERROR: No matching distribution found for ale-py

**Comment by pseudo-rnd-thoughts** [comment]
@gkennickell It might not be too difficult. you would need to modify the `pyproject.toml` options for `cibuildwheel` to add an linux arm64
This might require another custom linux docker image like the linux x86, but I believe that one should exist.

**Comment by pseudo-rnd-thoughts** [comment]
I've made a start in #609, the only remaining changes should be to update the aarch64 docker file to add any requirements
To debug, you can use `cibuildwheel` locally, just make sure to [keep the container](https://cibuildwheel.pypa.io/en/stable/options/#cibw_debug_keep_container) to be able to inspect any errors

**Comment by gkennickell** [comment]
Thanks. I've added info to https://github.com/Farama-Foundation/Arcade-Learning-Environment/pull/609 on the changes needed.
