### ISSUE TITLE
Got RuntimeError when running command-line tool ale-import-roms

### ISSUE THREAD

**Issue by ZM-J** [Farama-Foundation/Arcade-Learning-Environment#489]
Hi! I followed the instructions "Deep Q-Learning for Atari Breakout" from [Keras](https://keras.io/examples/rl/deep_q_network_breakout/). The [source code](https://github.com/keras-team/keras-io/blob/master/examples/rl/deep_q_network_breakout.py) requires [atari-py](https://github.com/openai/atari-py), but it seems that ale-py, i.e., this repo, is recommended. Therefore, I pip-installed this repo, and tried running

```
ale-import-roms .\ROMS\
```

However, I got a RuntimeError:

```
Traceback (most recent call last):
  File "D:\Software\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Software\Anaconda\Scripts\ale-import-roms.exe\__main__.py", line 7, in <module>
  File "D:\Software\Anaconda\lib\site-packages\ale_py\scripts\import_roms.py", line 93, in main
    import_roms(romdir, datadir, pkg=args.import_from_pkg, dry_run=args.dry_run)
  File "D:\Software\Anaconda\lib\site-packages\ale_py\scripts\import_roms.py", line 25, in import_roms
    rom = ale_py.ALEInterface.isSupportedROM(path)
RuntimeError
```

I got the ROMs in the [Atari 2600 VCS ROM Collection](http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html).

**Comment by pseudo-rnd-thoughts** [comment]
`ale-import-roms` is deprecated and no longer needed
